//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace пр5модули.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class HospitalProEntities : DbContext
    {
        public HospitalProEntities()
            : base("name=HospitalProEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Departament> Departament { get; set; }
        public virtual DbSet<Drugs> Drugs { get; set; }
        public virtual DbSet<DrugsInDepartament> DrugsInDepartament { get; set; }
        public virtual DbSet<Finance> Finance { get; set; }
        public virtual DbSet<Hospitalizations> Hospitalizations { get; set; }
        public virtual DbSet<Patient> Patient { get; set; }
        public virtual DbSet<PatientCard> PatientCard { get; set; }
        public virtual DbSet<Prescriptions> Prescriptions { get; set; }
        public virtual DbSet<Recordind> Recordind { get; set; }
        public virtual DbSet<Reports> Reports { get; set; }
        public virtual DbSet<Service> Service { get; set; }
        public virtual DbSet<Staff> Staff { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Ward> Ward { get; set; }
        public virtual DbSet<WardInDepartament> WardInDepartament { get; set; }
    }
}
