//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace пр5модули.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DrugsInDepartament
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DrugsInDepartament()
        {
            this.Prescriptions = new HashSet<Prescriptions>();
        }
    
        public int ID_drugs_in_departament { get; set; }
        public int ID_drug { get; set; }
        public int ID_departament { get; set; }
        public int dosage { get; set; }
        public int frequency { get; set; }
        public string duration { get; set; }
    
        public virtual Departament Departament { get; set; }
        public virtual Drugs Drugs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Prescriptions> Prescriptions { get; set; }
    }
}
