//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace пр5модули.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Finance
    {
        public int ID_finance { get; set; }
        public int ID_departament { get; set; }
        public int ID_patient { get; set; }
        public int ID_service { get; set; }
        public System.DateTime date_created { get; set; }
    
        public virtual Departament Departament { get; set; }
        public virtual Patient Patient { get; set; }
        public virtual Service Service { get; set; }
    }
}
