//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace пр5модули.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hospitalizations
    {
        public int ID_hospitalization { get; set; }
        public int ID_patient { get; set; }
        public int ID_ward_in_departament { get; set; }
        public System.DateTime admission_date { get; set; }
        public string diagnosis { get; set; }
    
        public virtual Patient Patient { get; set; }
        public virtual WardInDepartament WardInDepartament { get; set; }
    }
}
