//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace пр5модули.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PatientCard
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PatientCard()
        {
            this.Patient = new HashSet<Patient>();
        }
    
        public int ID_patient_card { get; set; }
        public int ID_patient { get; set; }
        public System.DateTime date_of_birth { get; set; }
        public string gender { get; set; }
        public string addres { get; set; }
        public string phone_number { get; set; }
        public string INN_number { get; set; }
        public string medical_history { get; set; }
        public string alligries { get; set; }
        public string medications { get; set; }
        public string blood_type { get; set; }
        public string rh_phactor { get; set; }
        public string weight { get; set; }
        public System.DateTime last_visit_date { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Patient> Patient { get; set; }
        public virtual Patient Patient1 { get; set; }
    }
}
