//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace пр5модули.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Prescriptions
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Prescriptions()
        {
            this.Patient = new HashSet<Patient>();
        }
    
        public int ID_prescription { get; set; }
        public int ID_patient { get; set; }
        public int ID_drugs_in_departament { get; set; }
        public System.DateTime date_created { get; set; }
        public int ID_doctor { get; set; }
        public System.DateTime next_meeting { get; set; }
    
        public virtual DrugsInDepartament DrugsInDepartament { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Patient> Patient { get; set; }
        public virtual Patient Patient1 { get; set; }
    }
}
