//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace пр5модули.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reports
    {
        public int ID_report { get; set; }
        public int ID_doctor { get; set; }
        public int ID_record { get; set; }
        public string diagnos { get; set; }
        public int ID_patient { get; set; }
        public int ID_service { get; set; }
        public string problems { get; set; }
        public byte[] drugs { get; set; }
        public System.DateTime next_meeting { get; set; }
    
        public virtual Patient Patient { get; set; }
        public virtual Recordind Recordind { get; set; }
        public virtual Service Service { get; set; }
        public virtual Staff Staff { get; set; }
    }
}
