//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace пр5модули.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WardInDepartament
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public WardInDepartament()
        {
            this.Hospitalizations = new HashSet<Hospitalizations>();
        }
    
        public int ID_ward_in_departament { get; set; }
        public int ID_ward { get; set; }
        public int ID_departament { get; set; }
    
        public virtual Departament Departament { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Hospitalizations> Hospitalizations { get; set; }
        public virtual Ward Ward { get; set; }
    }
}
